config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.views import MaterialCreateView, MaterialUpdateView, MaterialListView, MaterialDetailView, MaterialDeleteView
from materials.apps import MaterialsConfig
from django.views.decorators.cache import never_cache
app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', never_cache(MaterialCreateView.as_view()), name='create_materials'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', never_cache(MaterialUpdateView.as_view()), name='update_materials'),
    path('delete/<int:pk>/', never_cache(MaterialDeleteView.as_view()), name='delete_materials')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('activate-user/<str:token>/', VerifyEmailView.as_view(), name='activate_user'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/', PasswordResetSentView.as_view(), name='password-reset-sent'),
    path('<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password')
]

materials/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Materials(models.Model):
    title = models.CharField(max_length=20, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    picture = models.ImageField(upload_to='bloging/', verbose_name='превью', **NULLABLE)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}'
    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

materials/views.py
from materials.models import Materials
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
class MaterialCreateView(LoginRequiredMixin, CreateView):
    model = Materials
    fields = ('title', 'content', 'picture')
    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.object.pk])


class MaterialListView(LoginRequiredMixin, ListView):
    model = Materials

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

class MaterialDetailView(LoginRequiredMixin, DetailView):
    model = Materials


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MaterialUpdateView(LoginRequiredMixin, UpdateView):
    model = Materials
    fields = ('title', 'content', 'picture')
    success_url = reverse_lazy('materials:list')


class MaterialDeleteView(LoginRequiredMixin, DeleteView):
    model = Materials
    success_url = reverse_lazy('materials:list')

materials/templates/materials/material_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>Хотите удалить материал "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'materials:list' %}" class="btn btn-wrning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags%}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Материалы</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.picture|mediapath }}" alt="image" height=200px width=300px>
                    <h1 class="card-title pricing-card-title"> Материал {{ object|title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.title }}</li>
                        <li>- {{ object.content }}</li>
                        <li>- {{ object.time_create }}</li>
                        <li>- {{ object.is_published }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'materials:list' %}">Назад</a>
                      </div>
            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{ object.picture}}">
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p}}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/material_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'materials:create_materials' %}">Добавить материал</a>
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">{{ object|title }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'materials:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'materials:update_materials' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'materials:delete_materials' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}

materials/templates/materials/materials_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>Хотите удалить материал "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'materials:list' %}" class="btn btn-wrning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/materials_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags%}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Материалы</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.picture|mediapath }}" alt="image" height=200px width=300px>
                    <h1 class="card-title pricing-card-title"> Материал {{ object|title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.title }}</li>
                        <li>- {{ object.content }}</li>
                        <li>- {{ object.time_create }}</li>
                        <li>- {{ object.is_published }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'materials:list' %}">Назад</a>
                      </div>
            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p}}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/materials_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'materials:create_materials' %}">Добавить материал</a>
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">{{ object|title }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'materials:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'materials:update_materials' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'materials:delete_materials' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}