config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('activate-user/<str:token>/', VerifyEmailView.as_view(), name='activate_user'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/', PasswordResetSentView.as_view(), name='password-reset-sent'),
    path('<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from catalog.models import NULLABLE

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')


    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=40, verbose_name='страна')
    is_active = models.BooleanField(default=False, verbose_name='статус активности')
    email_verificator = models.CharField(max_length=25, **NULLABLE, verbose_name='код верификации почты')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from users.models import User
from django import forms


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.ChoiceField):
                field.widget.attrs['class'] = 'form-select'
            elif isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

class StylePasswordResetMixin:
    """
   Обновление стилей форм восстановления пароля
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control mt-2',
                'autocomplete': 'off'
            })

class UserLoginForm(StyleFormMixin, AuthenticationForm):
    """
    Форма авторизации на сайте
    """
    pass
class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserForgotPasswordForm(StylePasswordResetMixin, PasswordResetForm):
    """
    Запрос на восстановление пароля
    """
    pass

class UserSetNewPasswordForm(StylePasswordResetMixin, SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """
    pass

class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string
import os
from django.shortcuts import render
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.template.loader import render_to_string
from django.views.generic import CreateView, UpdateView, TemplateView
from users.models import User
from users.forms import UserRegisterForm, UserProfileForm, UserForgotPasswordForm, UserSetNewPasswordForm
from django.urls import reverse_lazy,reverse
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import redirect
from django.views import View
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.mixins import LoginRequiredMixin



class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_engine = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        new_user = form.save()
        # Создаем и сохраняем токен подтверждения
        token = ''.join(random.choices(string.ascii_letters + string.digits, k=25))
        new_user.email_verificator = token
        new_user.save()
        # Отправляем письмо с подтверждением
        current_site = get_current_site(self.request)
        mail_subject = 'Conrirm registration'
        message = render_to_string(
            'users/email_check.html',
            {
                'domain': current_site.domain,
                'token': token,
            },
        )
        send_mail(mail_subject, message, os.getenv('EMAIL_HOST_USER'), [new_user.email])
        return response


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class VerifyEmailView(View):
    """
    Представление верификации нового пользователя по почте
    """

    def get(self, request, token):
        try:
            user = User.objects.get(email_verificator=token)
            user.is_active = True
            user.save()
            return redirect('users:email_confirmed')
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            return redirect('users:email_confirmation_failed')


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class UserForgotPasswordView(PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:password-reset-sent')
    subject_template_name = 'users/password_subject_reset_mail.txt'
    email_template_name = 'users/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на сброс пароля'
        return context


class PasswordResetSentView(TemplateView):
    template_name = 'users/password_reset_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо отправлено'
        return context


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context

class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        return context


def generate_new_password(request):
    new_password = ''.join([str(random.randint(1, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()

    return redirect(reverse('catalog:index'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-6">
      <div class="card">
          <div class="card-header">
              <h2 class="card-title">
                  Вход
              </h2>
          </div>
          <div class="card-body">
              <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-success">Войти</button>
              </form>
          </div>
          <div class="card-footer"></div>

      </div>
  </div>
   <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p}}
                        {% if not forloop.last %}
                        <hr class="m-4" />
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-6">
      <div class="card">
          <div class="card-header">
              <h2 class="card-title">
                  Регистрация
              </h2>
          </div>
          <div class="card-body">
              <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-success">Регистрация</button>
              </form>
          </div>
          <div class="card-footer"></div>

      </div>
  </div>
   <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p}}
                        {% if not forloop.last %}
                        <hr class="m-4" />
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
  </div>
  <div class="col-6">
      <div class="card">
          <div class="card-header">
              <h2 class="card-title">
                  Профиль
              </h2>
          </div>
          <div class="card-body">
              <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-success">Сохранить</button>
              </form>
          </div>
          <div class="card-footer">
              <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
          </div>

      </div>
  </div>
   <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p}}
                        {% if not forloop.last %}
                        <hr class="m-4" />
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}