catalog/urls.py
from django.urls import path
from catalog.views import ProductListView, ContactListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView
from catalog.apps import MainConfig
from django.views.decorators.cache import cache_page, never_cache
app_name = MainConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', ContactListView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create/', never_cache(ProductCreateView.as_view()), name='create_products'),
    path('update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.views import MaterialCreateView, MaterialUpdateView, MaterialListView, MaterialDetailView, MaterialDeleteView
from materials.apps import MaterialsConfig
from django.views.decorators.cache import never_cache
app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', never_cache(MaterialCreateView.as_view()), name='create_materials'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', never_cache(MaterialUpdateView.as_view()), name='update_materials'),
    path('delete/<int:pk>/', never_cache(MaterialDeleteView.as_view()), name='delete_materials')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('activate-user/<str:token>/', VerifyEmailView.as_view(), name='activate_user'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/', PasswordResetSentView.as_view(), name='password-reset-sent'),
    path('<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password')
]

catalog/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    picture = models.ImageField(upload_to='products/', verbose_name='превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='авторизованный пользователь')
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'
    class Meta:
        permissions = [
            (
                'set_published_status',
                 'Can publish post'
            ),
            (
                'changing_the_description',
                'Can change the description'
            ),
            (
                'changing_the_category',
                'Can change the category'
            )
        ]
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('price',)


class Contact(models.Model):
    name = models.CharField(max_length=150, verbose_name='название')
    address = models.CharField(max_length=40, verbose_name='адрес')
    phone = models.CharField(max_length=10, verbose_name='телефон')
    email = models.EmailField(verbose_name='email')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number_version = models.IntegerField(verbose_name='номер версии')
    name_version = models.CharField(max_length=100, verbose_name='название версии')
    version_indication = models.BooleanField(default=True, verbose_name='признак версии')

    def __str__(self):
        return f'{self.number_version} {self.name_version}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'price',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.stop_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for stopword in self.stop_list:
            if stopword in cleaned_data:
                raise forms.ValidationError('Название содержит недопустимые слова')
        return cleaned_data


    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for stopword in self.stop_list:
            if stopword in cleaned_data:
                raise forms.ValidationError('Описание содержит недопустимые слова')
        return cleaned_data
class VersionForm(forms.ModelForm):

    class Meta:
         model = Version
         fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from catalog.models import Product, Contact, Version, Category
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from catalog.forms import ProductForm, VersionForm
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import Http404
from catalog.services import get_cache_for_categories

# Create your views here.


class ProductListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Product
    permission_required = 'catalog.view_product'
    extra_context = {
        'title': 'Главная'
    }

class ContactListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Contact
    permission_required = 'catalog.view_product'
    template_name = 'catalog/contacts.html'



class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    permission_required = 'catalog.view_product'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['name'] = str(context['object'])
            context['version'] = Version.objects.filter(product=self.kwargs['pk'], version_indication=True).order_by('pk')
            print(context['version'])
            return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание товара'
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = VersionFormset(self.request.POST)
        else:
            context['formset'] = VersionFormset()
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404

        return self.object
    def get_success_url(self):
        return reverse('catalog:product', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменение товара'
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context['formset'] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data().get('formset')
        if formset.is_valid():
            actual_version_count = 0
            for f in formset:
                if f.cleaned_data.get('version_indication'):
                    actual_version_count += 1
                    if actual_version_count > 1:
                        form.add_error(None, "Вы можете выбрать только одну активную версию")
                        return self.form_invalid(form=form)
            formset.save()
        return super().form_valid(form)

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    def test_func(self):
        return self.request.user.is_superuser


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'catalog/categories.html'

    def get_queryset(self):
        return get_cache_for_categories(Category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список категорий'
        return context

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
{% block content %}
{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>788-334-15-22</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Германия, 98064-7455</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email" placeholder="Ваш адрес электропочты" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Расскажите, о чём вы хотите сообщить?" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load my_tags%}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Лучшие товары</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.picture|mediapath }}" alt="image" height=200px width=300px>
                    <h1 class="card-title pricing-card-title">{{ object|title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.price }}</li>
                        <li>- {{ object.description|truncatechars:100 }}</li>
                        <li>- {{ object.category }}</li>

                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Купить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags%}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Лучшие товары</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.picture|mediapath }}" alt="image" height=200px width=300px>
                    <h1 class="card-title pricing-card-title">{{ object|title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.price }}</li>
                        <li>- {{ object.description }}</li>
                        <li>- {{ object.category }}</li>
                        <li>- {{ object.time_create }}</li>
                        <li>- {{ object.time_update }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Назад</a>
                      </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>Хотите удалить продукт "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'materials:list' %}" class="btn btn-wrning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Материалы</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.picture|mediapath }}" alt="image" height=200px width=300px>
                    <h1 class="card-title pricing-card-title">{{ object|title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.price }}</li>
                        <li>- {{ object.description }}</li>
                        <li>- {{ object.category }}</li>
                        <li>- {{ object.time_create }}</li>
                        <li>- {{ object.time_update }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_update' object.pk %}">Редактировать</a>
                    {% if user.is_superuser %}
                    <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
                    {% endif %}
           {% if version %}
            <small class="d-block mb-3 text-muted">Актуальная версия:

                {{ version }}


            </small>
            {% endif %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Назад</a>
                      </div>
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{ object.picture}}">
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-6">
      <div class="card">
          <div class="card-header">
              <h2 class="card-title">
                  Добавление продукта
              </h2>
          </div>
          <div class="card-body">
              <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-success">Сохранить</button>
              </form>
          </div>
          <div class="card-footer"></div>

      </div>
  </div>
   <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p}}
                        {% if not forloop.last %}
                        <hr class="m-4" />
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags%}
{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
    <div class="row text-center">
        <div class="col-12 mb-5">
    {% if perms.catalog.add_product %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_products' %}">Добавить прродукт</a>
    {% endif %}
        </div>
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Лучшие товары</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.picture|mediapath }}" alt="image" height=200px width=300px>
                    <h1 class="card-title pricing-card-title">{{ object|title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.price }}</li>
                        <li>- {{ object.description|truncatechars:100 }}</li>
                        <li>- {{ object.category }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Купить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}